### ISSUE TITLE
The final selector does not respect the inheritance specification

### ISSUE THREAD

**Issue by kawazoe** [jonathantneal/postcss-dir-pseudo-class#3]
# The issue
The way the polyfill works currently is by replacing the `:dir(x)` selector with a `[dir="x"]` prefix. This causes issue when it comes to the respect of the specification as the dir selector needs to respect the inheritance of the dir attribute's value through the DOM. For instance:

```html
<body style="padding: 25px">
<div dir=rtl>
  outter
  <div>
    middle
    <div dir=ltr>
      inner
      <div>
        deep
      </div>
    </div>
  </div>
</div>
</body>
```

```css
div:dir(ltr) { border: 2px solid red; }
div:dir(rtl) { border: 2px solid green; }
```

|          | outter | middle | inner | deep  |
|----------|--------|--------|-------|-------|
| Actual   | none (1)   | green  | green (1) | green (2) |
| Expected | green  | green  | red   | red   |

You can play with it here: https://codepen.io/anon/pen/dLXRYj

# Why it happens

The first discrepancies (outer without border and inner not red) happen because you do not include the element with the attribute in the generated selector. The current output is basically "any div WITHIN something with a dir attribute" instead of "any div WITH a dir attribute".

The second discrepancy (deep not red) happens because the deepest div matches both selector and so green being declared last wins. Only `:dir(ltr)` should match deep since the value of the dir attribute should propagate down the DOM hierarchy. In other words, this HTML code is functionally equivalent to declaring the dir attribute on each element with a CSS selector that only matches an element with the dir attribute. Aka:

```html
<body style="padding: 25px">
<div dir=rtl>
  outter
  <div dir=rtl>
    middle
    <div dir=ltr>
      inner
      <div dir=ltr>
        deep
      </div>
    </div>
  </div>
</div>
</body>
```

```css
div[dir=ltr] { border: 2px solid red; }
div[dir=rtl] { border: 2px solid green; }
```

# A solution?
This is a very important behavior as many RTL sites will contain at least some LTR elements and need to switch back and forth through the DOM hierarchy and not just globally for the entire site.

As far as I am aware, the only way to properly approximate this behavior is by using the `:lang(x)` selector which also have the same inheritance constraints. What I usually do in my sites is to generate a selector for each RTL language that I support. For instance,

```css
.some #complicated.selector:dir(rtl) { ... }
```

would become

```css
.some #complicated.selector:lang(ar),
.some #complicated.selector:lang(fa) { ... }
```
if I support Arabic and Farsi.

Obviously, this is far from perfect. It requires the use of the `lang` attribute instead of `dir`, and could generate some very heavy selectors when you support many languages. Unfortunately, it is also the only way that I know to polyfill dir correctly without any run-time shenanigans.

Do you think this would be an interesting feature to add to this polyfill?

**Comment by romainmenke** [comment]
Hi @kawazoe 

We did our best to improve support for more complex selectors in the last release. (https://github.com/csstools/postcss-plugins/pull/62)
True inheritance is something we can not add support for unfortunately.

If it was possible to have true inheritance and good support for all possible CSS selectors with only an attribute there would have been no need for the `:dir()` pseudo in the first place :)

Overloading `:lang()` would be problematic in the context of this plugin and `postcss-preset-env`. The ultimate goal of any polyfill-like software is to become obsolete and disappear. If we hijack `:lang()` it would require creators to write specific markup that will never work natively in browsers without this plugin.

Going to close this issue as the repo has been moved to https://github.com/csstools/postcss-plugins

Feel free to open a new issue there if you have more thoughts are a good idea to get better inheritance support!
